name: Deploy Frontend Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Production
        run: |
          flutter build web --release \
            --dart-define=BASE_URL=http://56.125.23.170:5113 \
            --dart-define=API_KEY=${{ secrets.API_KEY_PROD }}

      - name: Prepare wwwroot directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: mkdir -p ~/aisend-api/wwwroot

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/web/*"
          target: "~/aisend-api/wwwroot"
          strip_components: 2

      - name: Restart backend to serve new frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart aisend-api
